name: Rust

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Install musl rs toolchain
      uses: actions-rs/toolchain@v1
      with:
          target: x86_64-unknown-linux-musl
          profile: minimal
          override: true
          toolchain: stable
    - name: Build
      run: cargo build --target x86_64-unknown-linux-musl --release --verbose
