name: Rust

on:
  - push
  - pull_request

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Install musl rs toolchain
      uses: actions-rs/toolchain@v1
      with:
          target: x86_64-unknown-linux-musl
          profile: minimal
          override: true
          toolchain: stable
    - name: Build
      run: cargo build --target x86_64-unknown-linux-musl --release --verbose

    - name: Deploy - Create Release
      if: startsWith(github.ref, 'refs/tags/')
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.ref_name }}
        release_name: ${{ github.ref_name }}
        draft: false
        prerelease: false

    - name: Deploy - Upload Release
      if: startsWith(github.ref, 'refs/tags/')
      id: upload-release-asset 
      uses: csexton/release-asset-action@v2
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        release-url: ${{ steps.create_release.outputs.upload_url }}
        pattern: target/x86_64-unknown-linux-musl/release/rsync-speedtest
